### ISSUE TITLE
Error when using template

### ISSUE THREAD

**Issue by andreasbecker** [juban/craft-newsletter#3]
Hi, 

I get the following error when using the provided twig template to show the form
![Bildschirmfoto 2022-08-12 um 17 20 20](https://user-images.githubusercontent.com/661734/184387040-0b9122a3-31e7-4169-a761-1578de496b6f.png)

Can you help?

**Comment by juban** [comment]
Hi @andreasbecker 

Are you sure to use the latest version (2.1.0) of this plugin and require `jub/craft-newsletter` in you composer.json file?
The plugin just changed it signature, so the provided exemple will only work with latest version.
