### ISSUE TITLE
The newsletter service is not available at that time

### ISSUE THREAD

**Issue by LieselotV** [juban/craft-newsletter#4]
Hi,

I use your plugin to get people to subscribe to our mailing list in mailchimp.

I applied all the right API and keys.
I used same form as your code suggestions.

When I enter a mail address I get this message:
_The newsletter service is not available at that time. Please, try again later._

**Comment by juban** [comment]
Hi @LieselotV

If you get that message, something is probably going wrong on the Mailchimp end (network issue, keys...).
You can check you logs by searching `Mailchimp` to see the exact error returned when the Mailchimp API is called.

**Comment by juban** [comment]
@LieselotV Feel free to reopen the issue if further help is needed.
